### ISSUE TITLE
Manage SASS compiling for deployed app

### ISSUE THREAD

**Issue by beardscratcher** [GIGGYPOP/giggypop_mvp#2]
To save ourselves future merge headaches, I'd like to keep the compiled app.css out of source control. Thinking of adding a git-hook to run the compile step i.e. on post-merge, but that may become annoying. 

Alternatively, not sure if there's something in the heroku deployment that can run grunt tasks?

Will investigate.

**Comment by ohwhen** [comment]
Good idea!

There is a grunt buildpack for Heroku, adding it to the current build is pretty straightforward :)

1. Add buildpack to Heroku `heroku config:add BUILDPACK_URL=https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt.git`
2. Add `Gruntfile.js` to project
3. Add dependecies to `package.json`

Then `git push heroku master` and all should build
https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt#usage
